version: '3'
services:
  nginx:
    image: nginx:latest
    restart: unless-stopped
    volumes:
       - /dev/null:/var/www/html/index.php
       - ./docker-data/public-files:/var/www/html/files
       - ./docker-data/assets:/var/www/html/assets

  ##### versão sem ssl
       - ./compose/production/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
       - '8080:80'
       - "8443:443"
    depends_on:
       - mapasculturais
    links:
       - mapasculturais


  mapasculturais:
    env_file:
       - .env
    build:
       context: ./
       dockerfile: compose/production/Dockerfile
    restart: unless-stopped
   #  ports:
      #  - '9000:9000'
    volumes:
       - ./.env:/.env
       - ./docker-data/assets:/var/www/html/assets
       - ./docker-data/public-files:/var/www/html/files
       - ./docker-data/private-files:/var/www/private-files
       - ./docker-data/saas-files:/var/www/SaaS
       - ./themes/Ceara/layouts/parts/charts/line.php:/var/www/html/protected/application/lib/modules/Charts/layouts/parts/charts/line.php
       # arquivos temporários
       - ./themes/Ceara/Entities/Opportunity.php:/var/www/html/protected/application/lib/MapasCulturais/Entities/Opportunity.php
       - ./themes/Ceara/Controllers/Registration.php:/var/www/html/protected/application/lib/MapasCulturais/Controllers/Registration.php
    links:
       - db
       - redis
       - sessions
    environment:
       - ACTIVE_THEME=Ceara
       - LOG_LEVEL=DEBUG
       - LOG_ENABLED=true
       - APP_MODE=production
       - APP_LCODE=pt_BR
         #      - APP_LCODE=pt_BR,es_ES # para selecao do idioma baseado no navegador
       - REDIS_CACHE=redis
       - SESSIONS_SAVE_PATH=tcp://redis:6379
       - PENDING_PCACHE_RECREATION_INTERVAL=5
    depends_on:
       - db
       - redis
       - sessions

  redis:
    image: redis:6
    command: --maxmemory 256Mb --maxmemory-policy allkeys-lru
    restart: unless-stopped 

  sessions:
    image: redis:6
    command: --maxmemory 384Mb --maxmemory-policy allkeys-lru
    restart: unless-stopped
    volumes:
      - ./docker-data/sessions:/data

  db:
    image: postgis/postgis:14-master
    restart: always
    environment:
       - POSTGRES_PASSWORD=mapas
       - POSTGRES_USER=mapas
       - POSTGRES_DB=mapas
       - POSTGRES_DB_TEST=mapasculturais_test
   #  ports:
      #  - '5438:5432'
    volumes:
       - ./docker-data/db-data:/var/lib/postgresql/data 750
       - ./compose/local/dump.sql:/docker-entrypoint-initdb.d/dump.sql
         #- ./docker-data/db-data:/var/lib/postgresql/data

