FROM hacklab/mapasculturais:v5.7.1-cli

COPY compose/common/config.php /var/www/html/protected/application/conf/config.php

COPY themes /var/www/html/protected/application/themes
COPY plugins /var/www/html/protected/application/plugins