version: '2'
services:
  mapas:
    env_file:
      - .env
    build:
      context: ../
      dockerfile: compose/local/Dockerfile
    
    ports:
      - "8080:80"
    volumes:
      - ./.env:/.env
      - ../docker-data/assets:/var/www/html/assets
      - ../docker-data/public-files:/var/www/html/files
      - ../docker-data/private-files:/var/www/private-files

      - ../compose/common/config.d:/var/www/html/protected/application/conf/conf-common.d
      - ../compose/local/config.d:/var/www/html/protected/application/conf/config.d
      - ../compose/local/mc-updates.php:/var/www/html/protected/mc-updates.php
      # themes and plugins
      - ../core/src/protected/application/lib/MapasCulturais/Controllers/Opportunity.php:/var/www/html/protected/application/lib/MapasCulturais/Controllers/Opportunity.php
      - ../core/src/protected/application/lib/MapasCulturais/Entities/Opportunity.php:/var/www/html/protected/application/lib/MapasCulturais/Entities/Opportunity.php
      - ../themes/Ceara:/var/www/html/protected/application/themes/Ceara
      - ../plugins/MultipleLocalAuth:/var/www/html/protected/application/plugins/MultipleLocalAuth
      - ../plugins/EditRegistration:/var/www/html/protected/application/plugins/EditRegistration
    environment:
      - PENDING_PCACHE_RECREATION_INTERVAL=10
      - JOBS_INTERVAL=10
      - REDIS_CACHE=redis
      - APP_MODE=development
      - CACHE_ASSETS_URL=0
    depends_on:
      - db
      - redis
      # - mailhog
  
    stdin_open: true
    tty: true


  redis:
    image: redis:6
    command: --maxmemory 256Mb --maxmemory-policy allkeys-lru

  db:
    image: postgis/postgis:14-master
    environment:
      - POSTGRES_PASSWORD=mapas
      - POSTGRES_USER=mapas
      - POSTGRES_DB=mapas
    ports:
      - "5432:5432"
    volumes:
      - ../compose/local/dump.sql:/docker-entrypoint-initdb.d/dump.sql
      - db-data:/var/lib/postgresql/data

volumes:
  db-data:
  # mailhog: 
  #   image: mailhog/mailhog
  #   ports:
  #     - "8025:8025"

volumes:
  db-data: